### PR TITLE
Let processing array attempt to use cached previousRecipe like other machines

### PR DESCRIPTION
**Pull request by talchas**
The extra problem here is the machines being replaced, so we do
still recheck those whenever the inventory changed.

machineName + machineTierVoltage is sufficient at the moment since that's all that is used, but machineItemStack might be better, I just wasn't 100% sure what the mutability / equality risks were there.

The symptom to fix is large tick time usage - a PA with 16 IV macerators and a UV input bus full of cobblestone would take ~20ms due to the Recipe.matches being particularly slow when failing to match with a large input inventory. (Fixing that might not be a bad idea, but would be a lot harder, and probably would require API changes for a real benefit)

### CODE REVIEW

**Comment by Exaxxion** [comment]
Sorry for the inconvenience but I recently refactored this class to address some concerns about its implementation. Please resolve the merge conflicts so we can proceed with reviewing your pull request.

**Comment by talchas** [comment]
Was just formatting changes in the relevant code, so no problems resolving the conflicts.

**Comment by Exaxxion** [comment]
This latest force push reverted the merge conflicts resolution commit you did previously. A force push should not have been necessary here.

**Comment by Exaxxion** [comment]
I have restored the original commit history from the reflog. Please make any changes to the current feature branch HEAD commit and do not force push.

**Comment by Exaxxion** [comment]
Closing since #112 incorporates the proposed behavior changes

**Pull request closed without merging**
