### PR TITLE
Gregtech update

### PR DESCRIPTION
**Pull request by ALongStringOfNumbers**
Updates Gregtech to its latest version.
Implements Fluid Tooltips and Multiblock default zoom from that update

### CODE REVIEW

**Review by Exaxxion — APPROVED** [review]

**Review by Exaxxion — APPROVED** [review]
Good catch on the version matching, we need to remember to do this in the future.

**Comment by ALongStringOfNumbers** [comment]
We should only really change the required after value if we are depending on code in the new GTCE versions. There are a couple GTCE updates where we are not depending on any code changes in the new version, so the value should not be bumped in those cases.

Changing the value has the effect of not letting players into the game if they are on older GTCE versions, which is why I say it should be changed sparingly.

**Comment by Exaxxion** [comment]
Sure, that is certainly the case but I think we were already very unlikely to still have been compatible with GTCE 1.8.6.

**Comment by ALongStringOfNumbers** [comment]
Yeah, I meant for updates after this point

**Comment by Exaxxion** [comment]
Naturally. If we're still compatible with existing APIs, there's no reason to force a version bump.

**Pull request merged**
